// extension/popup.js
let alarmSound = null;

document.addEventListener("DOMContentLoaded", async () => {
  // --- 0. AUTO-OPEN CHECK ---
  const urlParams = new URLSearchParams(window.location.search);
  if (urlParams.has("alert")) {
    showRedAlert({
      threat_score: urlParams.get("score"),
      reason: urlParams.get("reason"),
    });
  }

  // --- 1. CLOSE & STOP ---
  document.getElementById("close-popup")?.addEventListener("click", () => {
    stopAlarm();
    window.close();
  });

  // --- 2. RESTORE STATE ---
  const { isScanning } = await chrome.storage.local.get(["isScanning"]);
  if (isScanning && !urlParams.has("alert")) setVisualState(true);

  // --- 3. START BUTTON ---
  document.getElementById("start-btn")?.addEventListener("click", async () => {
    const [tab] = await chrome.tabs.query({
      active: true,
      currentWindow: true,
    });
    if (!tab) {
      alert("Please open this on a YouTube tab!");
      return;
    }
    chrome.runtime.sendMessage({ type: "START_SENTRY", tabId: tab.id });
    await chrome.storage.local.set({ isScanning: true });
    setVisualState(true);
  });

  // --- 4. STOP BUTTON ---
  document.getElementById("stop-btn")?.addEventListener("click", async () => {
    chrome.runtime.sendMessage({ type: "STOP_SENTRY" });
    await chrome.storage.local.set({ isScanning: false });
    setVisualState(false);
  });

  // --- 5. LISTEN FOR ALERTS ---
  chrome.runtime.onMessage.addListener((request) => {
    if (request.type === "SCAM_ALERT") {
      showRedAlert(request.payload);
      if (document.getElementById("history-ui").style.display === "flex")
        renderHistory();
    }
  });

  // --- 6. DISMISS ---
  document.getElementById("reset-btn")?.addEventListener("click", () => {
    stopAlarm();
    document.getElementById("alert-ui").style.display = "none";
    document.getElementById("normal-ui").style.display = "flex";
    if (urlParams.has("alert")) window.close();
  });

  // --- TAB SWITCHING ---
  document.getElementById("view-history")?.addEventListener("click", () => {
    document.getElementById("view-history").classList.add("active");
    document.getElementById("view-home").classList.remove("active");
    document.getElementById("normal-ui").style.display = "none";
    document.getElementById("alert-ui").style.display = "none";
    document.getElementById("history-ui").style.display = "flex";
    renderHistory();
  });

  document.getElementById("view-home")?.addEventListener("click", () => {
    document.getElementById("view-home").classList.add("active");
    document.getElementById("view-history").classList.remove("active");
    document.getElementById("history-ui").style.display = "none";
    document.getElementById("alert-ui").style.display = "none";
    document.getElementById("normal-ui").style.display = "flex";
  });

  // --- REPORT & CLEAR ---
  document
    .getElementById("download-report")
    ?.addEventListener("click", generateNativeReport);
  document
    .getElementById("clear-history")
    ?.addEventListener("click", async () => {
      if (confirm("Delete all evidence?")) {
        await chrome.storage.local.set({ history: [] });
        renderHistory();
      }
    });
});

// --- NEW: NATIVE REPORT (Fixes Hindi Text) ---
async function generateNativeReport() {
  const { history } = await chrome.storage.local.get(["history"]);
  if (!history || history.length === 0) {
    alert("No evidence.");
    return;
  }

  let reportHTML = `
    <html>
      <head>
        <title>SentryAI Evidence Report</title>
        <style>
          body { font-family: 'Arial', sans-serif; padding: 40px; color: #333; }
          h1 { color: #d32f2f; border-bottom: 2px solid #d32f2f; padding-bottom: 10px; }
          .meta { margin-bottom: 30px; font-size: 14px; color: #555; }
          .incident { border: 1px solid #ddd; padding: 20px; margin-bottom: 20px; border-radius: 8px; background: #f9f9f9; page-break-inside: avoid; }
          .incident-header { display: flex; justify-content: space-between; font-weight: bold; margin-bottom: 10px; }
          .score { color: #d32f2f; }
          .transcript { background: #eee; padding: 10px; border-left: 4px solid #555; font-style: italic; margin: 10px 0; font-family: 'Nirmala UI', 'Arial', sans-serif; }
          img { max-width: 100%; border: 1px solid #ccc; margin-top: 10px; border-radius: 4px; }
          .footer { margin-top: 40px; font-size: 12px; text-align: center; color: #888; border-top: 1px solid #eee; padding-top: 10px; }
        </style>
      </head>
      <body>
        <h1>OFFICIAL CYBER CRIME EVIDENCE REPORT</h1>
        <div class="meta">
          <strong>Generated By:</strong> SentryAI Protection System<br>
          <strong>Date:</strong> ${new Date().toLocaleString()}<br>
          <strong>Status:</strong> Threat Detected
        </div>
  `;

  history.forEach((item, index) => {
    reportHTML += `
      <div class="incident">
        <div class="incident-header">
          <span>INCIDENT #${index + 1}</span>
          <span class="score">Risk Score: ${item.threat_score}/100</span>
        </div>
        <p><strong>Time:</strong> ${item.timestamp}</p>
        <p><strong>Reason:</strong> ${item.reason}</p>
        
        <p><strong>Transcript:</strong></p>
        <div class="transcript">${item.transcript || "Audio detected"}</div>
        
        ${
          item.screenshot
            ? `<p><strong>Suspect Feed:</strong></p><img src="${item.screenshot}" />`
            : ""
        }
      </div>
    `;
  });

  reportHTML += `
      <div class="footer">Evidence captured automatically by SentryAI.</div>
      <script>window.onload = function() { window.print(); }</script>
    </body></html>
  `;

  // Open new window and trigger print
  const win = window.open("", "_blank", "width=900,height=800");
  win.document.write(reportHTML);
  win.document.close();
}

// --- HISTORY RENDERER ---
async function renderHistory() {
  const { history } = await chrome.storage.local.get(["history"]);
  const list = document.getElementById("history-list");
  list.innerHTML = "";

  if (!history || history.length === 0) {
    list.innerHTML =
      "<p style='text-align:center; color:#666; font-size:12px; margin-top:20px;'>No evidence recorded.</p>";
    return;
  }

  history.forEach((item, index) => {
    const div = document.createElement("div");
    div.className = "history-item";

    div.innerHTML = `
      <div style="display:flex; justify-content:space-between; align-items:center; font-size:10px; color:#aaa;">
        <span>${item.timestamp}</span>
        <div>
            <span style="color:#ff0055; font-weight:bold; margin-right:8px;">SCORE: ${
              item.threat_score
            }</span>
            <span class="delete-btn" data-index="${index}" style="cursor:pointer; font-size:14px;">🗑️</span>
        </div>
      </div>
      <div style="margin:5px 0; font-size:12px; color:#fff;">${
        item.reason
      }</div>
      <div style="font-size:10px; color:#888; font-style:italic;">"${
        item.transcript || "Audio Content"
      }"</div>
      ${
        item.screenshot
          ? `<img src="${item.screenshot}" style="width:100%; border-radius:4px; margin-top:5px; border:1px solid #444;">`
          : ""
      }
    `;
    list.appendChild(div);
  });

  document.querySelectorAll(".delete-btn").forEach((btn) => {
    btn.addEventListener("click", async (e) => {
      const idx = e.target.getAttribute("data-index");
      const { history } = await chrome.storage.local.get(["history"]);
      history.splice(idx, 1);
      await chrome.storage.local.set({ history });
      renderHistory();
    });
  });
}

// --- VISUALS & SOUND ---
function setVisualState(active) {
  const shield = document.getElementById("shieldContainer");
  if (active) {
    shield?.classList.add("pulse-active");
    document.getElementById("statusText").innerText = "ACTIVE SCANNING";
    document.getElementById("statusText").style.color = "#00f2ff";
    if (document.getElementById("start-btn"))
      document.getElementById("start-btn").style.display = "none";
    if (document.getElementById("stop-btn"))
      document.getElementById("stop-btn").style.display = "block";
  } else {
    shield?.classList.remove("pulse-active");
    document.getElementById("statusText").innerText = "SYSTEM IDLE";
    document.getElementById("statusText").style.color = "#ffffff";
    if (document.getElementById("start-btn"))
      document.getElementById("start-btn").style.display = "block";
    if (document.getElementById("stop-btn"))
      document.getElementById("stop-btn").style.display = "none";
  }
}
function showRedAlert(data) {
  document.getElementById("normal-ui").style.display = "none";
  document.getElementById("history-ui").style.display = "none";
  document.getElementById("alert-ui").style.display = "flex";
  document.getElementById("score-val").innerText = data.threat_score;
  document.getElementById("alert-reason").innerText = data.reason;
  playAlarm();
}
function playAlarm() {
  if (!alarmSound) {
    alarmSound = new Audio(
      "https://actions.google.com/sounds/v1/alarms/beep_short.ogg"
    );
    alarmSound.loop = true;
    alarmSound.volume = 0.5;
  }
  alarmSound.play().catch((e) => console.log(e));
}
function stopAlarm() {
  if (alarmSound) {
    alarmSound.pause();
    alarmSound.currentTime = 0;
  }
}
